apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: pdfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: pdfs-backend:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: pdfs-secret
                  key: DATABASE_URL
          ports:
            - containerPort: 8010
