apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: pdfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: melooong/pdfs-frontend:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: pdfs-config
                  key: API_URL
          ports:
            - containerPort: 8501
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
          livenessProbe:
            tcpSocket:
              port: 8501
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8501
            initialDelaySeconds: 15
            periodSeconds: 10
