apiVersion: v1
kind: Secret
metadata:
  name: pdfs-secret
  namespace: pdfs
type: Opaque
data:
  POSTGRES_PASSWORD: cGRmczEyMzQ=
  DATABASE_URL: cG9zdGdyZXNxbDovL3BkZnM6cGRmczEyMzRAcG9zdGdyZXNxbDo1NDMyL3BkZnM=
